import json
from pathlib import Path

path = Path('public/verbs.json')
verbs = json.loads(path.read_text(encoding='utf8'))

# CEFR levels for each verb (A1, A2, B1, B2, C1)
level_map = {
    'abfahren': 'A2',
    'abholen': 'A2',
    'ankommen': 'A1',
    'arbeiten': 'A1',
    'aufräumen': 'A1',
    'begleiten': 'B1',
    'benutzen': 'A2',
    'besuchen': 'A1',
    'zeichnen': 'A1',
    'bringen': 'A1',
    'dürfen': 'A1',
    'denken': 'A1',
    'energiegeladen sein': 'B1',
    'essen': 'A1',
    'empfangen': 'B1',
    'erzählen': 'A2',
    'fahren': 'A1',
    'finden': 'A1',
    'fliegen': 'A1',
    'frei sein': 'A2',
    'sich freuen': 'A1',
    'geben': 'A1',
    'gehen': 'A1',
    'geliebt werden': 'B1',
    'glücklich sein': 'A1',
    'haben': 'A1',
    'heißen': 'A1',
    'hören': 'A1',
    'kaufen': 'A1',
    'kennen': 'A1',
    'kommen': 'A1',
    'können': 'A1',
    'küssen': 'A2',
    'lachen': 'A1',
    'langweilig sein': 'A2',
    'leben': 'A1',
    'leiden': 'B1',
    'lesen': 'A1',
    'lieben': 'A1',
    'machen': 'A1',
    'mögen': 'A1',
    'müssen': 'A1',
    'nehmen': 'A1',
    'niedergeschlagen sein': 'B1',
    'reisen': 'A1',
    'rufen': 'A2',
    'schauen': 'A1',
    'schreiben': 'A1',
    'schreien': 'A2',
    'scherzen': 'B1',
    'sehen': 'A1',
    'singen': 'A1',
    'sich quälen': 'B2',
    'sich streiten': 'A2',
    'sich treffen': 'A1',
    'sollen': 'A1',
    'spielen': 'A1',
    'sprechen': 'A1',
    'stark sein': 'A1',
    'streicheln': 'A2',
    'stehen': 'A1',
    'sitzen': 'A1',
    'schlafen': 'A1',
    'öffnen': 'A1',
    'schließen': 'A1',
    'warten': 'A1',
    'bezahlen': 'A1',
    'helfen': 'A1',
    'kochen': 'A1',
    'putzen': 'A1',
    'laufen': 'A1',
    'suchen': 'A1',
    'duschen': 'A1',
    'ankleiden': 'A1',
    'einkaufen': 'A1',
    'vorbereiten': 'A2',
    'telefonieren': 'A1',
    'mitnehmen': 'A1',
    'abwaschen': 'A1',
    'entspannen': 'A2',
    'tanzen': 'A1',
    'trauern': 'B1',
    'träumen': 'A1',
    'trinken': 'A1',
    'traurig sein': 'A1',
    'umarmen': 'A2',
    'verabschieden': 'B1',
    'vermissen': 'A2',
    'waschen': 'A1',
    'werden': 'A1',
    'wissen': 'A1',
    'wohnen': 'A1',
    'wütend sein': 'A1',
}

# Add level to each verb in correct position (after cases)
for verb in verbs:
    verb_key = verb.get('de', '').lower()
    verb['level'] = level_map.get(verb_key, 'A2')

# Save updated file
path.write_text(json.dumps(verbs, ensure_ascii=False, indent=2), encoding='utf8')
print(f'Added level to {len(verbs)} verbs')
